In [3]:
import numpy as np

In [4]:
minhaLista=[1,2,3]

In [6]:
minhaLista

[1, 2, 3]

In [7]:
np.array(minhaLista)

array([1, 2, 3])

In [8]:
minhaMatriz = [[1,2,3,],[4,5,6],[7,8,9]]

In [9]:
np.array(minhaMatriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(4) #matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.linspace(0,10,5) #Numeros igualmente espaçados

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.random.rand(3, 4)

array([[0.57973365, 0.10355481, 0.53250691, 0.84743451],
       [0.16603907, 0.7240788 , 0.53199656, 0.15184384],
       [0.67556296, 0.15044317, 0.60838615, 0.21340445]])

In [39]:
np.random.randn(3)

array([-1.02189221, -1.87450038,  0.43588653])

In [83]:
np.random.randint(0, 100, 10)

array([83,  8, 26, 50, 66, 80,  9, 56, 11, 21])

In [84]:
arr = np.random.randint(0, 100, 10)

In [85]:
arr

array([ 7, 64, 27, 27, 92, 69, 73, 96, 48, 13])

In [86]:
arr = arr.reshape((5,2))

In [90]:
arr

array([[ 7, 64],
       [27, 27],
       [92, 69],
       [73, 96],
       [48, 13]])

In [91]:
arr.shape #Forma do vetor

(5, 2)

In [92]:
arr.max()

96

In [93]:
arr.min()

7

In [95]:
arr.argmax()
arr.argmin()

0