In [5]:
import numpy as np
arr = np.arange(0, 30, 3)

In [6]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr[3]

9

In [8]:
arr[2:5]

array([ 6,  9, 12])

In [9]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [12]:
arr[2:] = 32

In [14]:
arr = np.arange(50).reshape(5,10)

In [18]:
arr[:3][:2]#Primeiro: Linha, Segundo: Coluna

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr2 = arr[:3].copy() #Criando um novo array e não uma referência

In [22]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [29]:
bol = arr1 > 10

NameError: name 'arr1' is not defined

In [28]:
arr[bol]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3